### ISSUE TITLE
SentiWn.p

### ISSUE THREAD

**Issue by Pooort** [kevincobain2000/sentiment_classifier#6]
File "site-packages/pkg_resources/__init__.py", line 1576, in get_resource_stream
    return open(self._fn(self.module_path, resource_name), 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'python3.5/site-packages/senti_classifier/data/SentiWn.p'

**Comment by kevincobain2000** [comment]
Not sure why, because file exists in location and in package_data

https://github.com/kevincobain2000/sentiment_classifier/blob/master/src/senti_classifier/data/SentiWn.p

https://github.com/kevincobain2000/sentiment_classifier/blob/master/setup.py#L11

**Comment by kevincobain2000** [comment]
Please do the following

```
git clone https://github.com/kevincobain2000/sentiment_classifier
cd sentiment_classifier
python setup.py install
```

Somehow pickled data is not bundled with ``pip``. Will look into it later


--------


##### Your Error

```
➜  git:(master) which senti_classifier
senti_classifier not found

➜  git:(master) pip install senti_classifier
Collecting senti-classifier
  Could not find a version that satisfies the requirement senti-classifier (from versions: )
No matching distribution found for senti-classifier
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
➜  git:(master) pip install sentiment_classifier
Collecting sentiment-classifier
  Downloading sentiment_classifier-0.7.tar.gz
Requirement already satisfied (use --upgrade to upgrade): nltk in /usr/local/lib/python2.7/site-packages (from sentiment-classifier)
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python2.7/site-packages (from sentiment-classifier)
Collecting argparse (from sentiment-classifier)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Building wheels for collected packages: sentiment-classifier
  Running setup.py bdist_wheel for sentiment-classifier ... done
  Stored in directory: /Users/p_kathuria/Library/Caches/pip/wheels/54/64/d9/90728610d02efd323949d2a54196bee272aa41402b386aadee
Successfully built sentiment-classifier
Installing collected packages: argparse, sentiment-classifier
Successfully installed argparse-1.4.0 sentiment-classifier-0.7
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
➜  git:(master) which senti_classifier
/usr/local/bin/senti_classifier
➜  git:(master) senti_classifier -c AFINN-111.txt
Traceback (most recent call last):
  File "/usr/local/bin/senti_classifier", line 223, in <module>
    senti_pickle = resource_stream('senti_classifier', 'data/SentiWn.p')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1177, in resource_stream
    self, resource_name
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1743, in get_resource_stream
    return open(self._fn(self.module_path, resource_name), 'rb')
IOError: [Errno 2] No such file or directory: u'/usr/local/lib/python2.7/site-packages/senti_classifier/data/SentiWn.p'
```


##### Fix

```
➜  tmp git clone https://github.com/kevincobain2000/sentiment_classifier
Cloning into 'sentiment_classifier'...
remote: Counting objects: 1631, done.
Receiving objects:  13% (216/1631), 9.82 MiB | 640.00 KiB/s
```


```
➜  sentiment_classifier git:(master) ✗ python setup.py install

Installed /usr/local/lib/python2.7/site-packages/sentiment_classifier-0.7-py2.7.egg
Processing dependencies for sentiment-classifier==0.7
Searching for argparse==1.4.0
Best match: argparse 1.4.0
Adding argparse 1.4.0 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Searching for numpy==1.11.2
Best match: numpy 1.11.2
Adding numpy 1.11.2 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Searching for nltk==3.2.1
Best match: nltk 3.2.1
Adding nltk 3.2.1 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Finished processing dependencies for sentiment-classifier==0.7
```

```
➜  sentiment_classifier git:(master) ✗ senti_classifier -c README.rst
0. Citations                            ... pos = 0       neg = 0
1. ---------                            ... pos = 0       neg = 0
3. This library is site                 ... pos = 0       neg = 0
5. http://www.aclweb.or                 ... pos = 0       neg = 0
8. iPhone App for Twitt                 ... pos = 0       neg = 0
9. --------------------                 ... pos = 0       neg = 0
11. https://itunes.apple                ... pos = 0       neg = 0
```
