### ISSUE TITLE
Trouble with Example Code

### ISSUE THREAD

**Issue by robbiebarrat** [kevincobain2000/sentiment_classifier#8]
I'm trying to run:
```
from senti_classifier import senti_classifier
sentences = ['The movie was the worst movie', 'It was the worst acting by the actors']
pos_score, neg_score = senti_classifier.polarity_scores(sentences)
print pos_score, neg_score
```

but i keep getting error

```
Traceback (most recent call last):
  File "/home/robbie/sentiment/sentiment.py", line 1, in <module>
    from senti_classifier import senti_classifier
  File "build/bdist.linux-x86_64/egg/senti_classifier/senti_classifier.py", line 227, in <module>
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1178, in resource_stream
    self, resource_name
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1454, in get_resource_stream
    return io.BytesIO(self.get_resource_string(manager, resource_name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1457, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1535, in _get
    return self.loader.get_data(path)
IOError: [Errno 0] Error: 'senti_classifier/data/SentiWn.p'
```

it looks like i don't have some sort of data file? Where do I get one or how do I make one? I thought it was already trained upon install.

**Comment by kevincobain2000** [comment]
Sorry for the trouble

Can you try re-installing via cloning please

```
➜  sentiment_classifier git:(master) ✗ python setup.py install
```

Ref: #6

**Comment by robbiebarrat** [comment]
it worked - i had to use nltk.download() to install a few packages after that, though.

I guess the problem was caused by the fact that pip doesn't download the data.

Thank you though - it's a great library!

**Comment by kevincobain2000** [comment]
Good to know! Thanks and all the best :)

**Comment by vrushabjain** [comment]
Hi, I am using Anaconda spyder version 3. Would I be able to download this package?
